[package]
name = "editor_widget"
version = "0.1.0"
edition = "2024"

[dependencies]
buffer = { path = "../buffer" }
global = { path = "../global" }
iced = { workspace = true }
iced_core = { workspace = true }
cosmic-text = { workspace = true }
